### ISSUE TITLE
Shortcut Translation Tables

### ISSUE THREAD

**Issue by rbreaves** [rbreaves/kinto#44]
## Kinto v1.0.5-8

**Kinto GUI**
Ctrl = Cmd Position
Super = Ctrl Position

**Kinto Term**
Ctrl+Shift = Cmd Position
Ctrl = Ctrl Position

## Base

|  **Behavior** | **Linux** | **macOS** | **Kinto GUI** | **Kinto Term** |
| --- | --- | --- | --- | --- |
|  Primary Modifier | Ctrl | Cmd | Alt/Cmd -> Ctrl | Alt/Cmd -> Ctrl+Shift |
|  Secondary Modifier | Alt | Alt | Win/Alt -> Alt | Win/Alt -> Alt |
|  Tertiary Modifier | Super (Win) | Ctrl | Ctrl -> Super | Ctrl -> Ctrl |

## Wordwise

|  **Behavior** | **Linux** | **macOS** | **Kinto GUI** | **Kinto Term** |
| --- | --- | --- | --- | --- |
|  Beginning of Line | Home | Cmd+Left | Ctrl+Left | N/A |
|  End of Line | End | Cmd+Right | Ctrl+Right | N/A |
|  Left of Word | Ctrl+Left | Alt+Left | Alt+Left | N/A |
|  Right of Word | Ctrl+Right | Alt+Right | Alt+Right | N/A |
|  Beginning of File | Ctrl+Home | Cmd+Up | Ctrl+Up | N/A |
|  End of File | Ctrl+End | Cmd+Down | Ctrl+Down | N/A |
|  Delete | Delete | Fn+Backspace | Alt+Backspace | N/A |

## Terminal

|  **Behavior** | **Linux** | **macOS** | **Kinto Term** |
| --- | --- | --- | --- |
|  Page Up | PageUp | Fn+Up | Ctrl+Shift+Up |
|  Page Down | PageDown | Fn+Down | Ctrl+Shift+Down |
|  Home | Home | Fn+Shift+Up/Left? | Ctrl+Shift+Left |
|  End | End | Fn+Shift+Down/Right? | Ctrl+Shift+Right |

**Comment by rbreaves** [comment]
Cycle Applications is done in dev. May have to resolve Change Workspace last, gnome defaults to vertical layouts unless an extension is installed. Also will have to enable the caret detection system-wide (general gui) otherwise Wordwise will conflict with Change Workspace shortcuts going in either vertical or horizontal. 

Early dev build has most of the shortcuts resolved besides Changing workspace and minimize window (Ctrl+H is used by many apps.. so remapping it to another combination may be difficult to do..).
https://github.com/rbreaves/kinto/commit/5003d6fa9b5b80388a87eb6ff7371b8e01ede8e1

**Comment by rbreaves** [comment]
Just to make note of a meaningful difference between xfce4 vs gnome or kde. Xfce4 does not typically support multiple hotkeys for a function of xwfm4, however other extensions and command for non-native xwfm4 actions is supported for multiple hotkeys. Still it isn't much help in assigning multiple hotkeys for any DE action.

This becomes somewhat meaningful due to the terminal keymap that defaults the Cmd position to Ctrl+Shift. It is seemingly not possible to retro-actively reset modifier keys after the destination key has been pressed - any remapping happens in a way that is disconnected from the keys you're actually pressing. This means remapping a modifier AFTER the destination key is pressed it initiates a tap on the modifier key you want (and may ignore the original modifier - if you set it to clear itself), but you can't really swap the modifier.

I may make a blog like post later better explaining this issue, if anyone thinks they have a solution on fixing that behavior in xkb then please reach out to me as I'd love to have a real solution for it. I can still do what I need to do, but it would make things a good bit easier to configure.

**Comment by mozmorris** [comment]
@rbreaves firstly, thank you for the work you're doing here. I can see this is in active development, but my initial impression has been positive :+1: 

I note above you say cycle application is done in dev so perhaps the following issue is already resolved.

**Context**
macOS keyboard
Ubuntu 19.10
Kinto: master 40b521ce09eccb524c5d21e9d50c750f898ab3ad

**Shortcut**
System Level -> Cycle Applications

**Keypress**
Cmd+tab _(Super+tab)_

**Current Focus**
Terminal

**Issue**
Cycle applications performs action in reverse

**Expected behaviour**
Cycle application performs action forwards

**Comment by rbreaves** [comment]
@mozmorris Yes lol, the app cycling in master would likely be in reverse, and I have been doing so many commits I honestly couldn't remember if I had included that in master at all just yet.

That isssue is resolved even now on the dev branch, and I think the current commit is stable for Ubuntu 19.10, and now even GalliumOS (although I have one ticket saying otherwise atm). You can try the current dev release if you'd like. I will be testing 2 or 3 OS's and making sure they all work and getting some KDE stuff going before merging it with master as it will bring online the rest of the most commonly used OS shortcuts.

https://github.com/rbreaves/kinto/commit/d45b8e29dc045c99cc11a2e75c58f7acd7241326

Also while the reversed app cycling has been resolved for the terminal on Gnome, I was not able to fix it on xfce4 (galliumOS) and any fix I can come up with atm would be worse than leaving it cycling backwards. I believe KDE won't be an issue either because like Gnome I can specify multiple shortcut keys for any given action, xfce4 does not allow that.

**Comment by mlbaquerizo** [comment]
@rbreaves +1 on the awesome work on this. There are a couple of other little issues I can see, not sure if this is the right place to bring them up so sorry in advance...
- in browser (firefox), when focused in a text input (like this github wysiwyg i'm typing in now), the **Beginning of Line** and **End of Line** shortcuts are overwritten by the **Back** and **Forward** browser shortcuts
- on the `dev` branch, the app cycling works as expected, but app window cycling (macOS - Command+backtick) does not. I would expect Alt+backtick to be mapped to this behavior. This behavior is still mapped to the Super+backtick, as in the master branch

**Comment by rbreaves** [comment]
@mlbaquerizo That is odd behavior for Firefox to not be defaulting back to using wordwise shortcuts while the input caret is active. I will have to do some testing later to see if I can replicate that in either master or dev. It could be an issue with either something about the polling of IBus for the caret status or the execution of xdotool even.

I am not sure about the backtick issue, it's not something I have been looking at that specifically. I may have messed with it some though in dev while working out how to best deal with Cmd+Tab. Cmd+Tab is challenging in general though because we're really working with Ctrl+Tab and the real Ctrl+Tab in both Linux and macOS tends to cycle in app tabs, while Alt is for apps in Linux and Cmd is for Apps in macOS.

What I end up having to do is re-remap Cmd+Tab (ctrl+tab) to Alt+Tab essentially and re-remap Ctrl+Tab (super+tab) back to Ctrl+Tab lol. It feels kinda hanky - but it works under Gnome and xfce for the most part - with enough work, but KDE is proving to be difficult as it doesn't like it when the real Alt key isn't being used.

Also app switching gets even more difficult under the Terminals, I believe the reverse cycling is broken on Terminals and will likely remain that way for awhile until I or someone else can find a way to resolve it. That is relatively minor though, I think.

And the only other alternative I can think of would be to completely change the keymap up and not place Ctrl where the Cmd key goes - but I refuse to do that just over app switching lol, because that can of worms is much worse and would lead to nothing good.

**Comment by rbreaves** [comment]
@mlbaquerizo I think the caret issue you experienced in Firefox is something that can sometimes happen, but hopefully very rarely. I duplicated it once just now, but it could be because I was doing it very quickly too (if you are fast enough the caret polling won't catch up as it polls at 0.5 seconds).

I could try lowering that value, but I feel like that could cause issues with a function I am using from the x11 library that waits for changes to occur as I had already tried other values too like 0.1, 0.2 and 0.3. I assume that function just needs a certain amount of time to fully initialize and if you try re-initializing too quickly it will crash the program in unexpected ways. It's a hard thing to balance tbh, because I am trying to do 2 things at once but only for the web browsers - monitor what program has the current focus and whether the caret input is active or not.

**Comment by mlbaquerizo** [comment]
it seemed to have been a constant occurance for me.
I had to uninstall for now because when I tried typing in a discord chat, pressing the `A` key selected all text (it behaved as Cmd+a) for some reason.
But keeping an eye on this project and will test when I can.
Thanks

**Comment by rbreaves** [comment]
@mlbaquerizo That select-all issue has been fixed in the dev branch as of yesterday. It unfortunately was introduced while implementing a feature request and only impacted Chrome or chromium based (electron) apps. Kinda a big bug I admit, but it has been resolved.

See this ticket for more details https://github.com/rbreaves/kinto/issues/52 and anything after commit https://github.com/rbreaves/kinto/commit/b9042356536bfd3835be4ac4af0a0349fccd6354 should have the bug fixed.

**Comment by mlbaquerizo** [comment]
The select-all issue is fixed in dev. Thanks!

Running Manjaro 19.0.2 Gnome edition
service log:
```
Mar 10 19:54:30 NOBLE-lnx systemd[4802]: Started keyswap for Terminal and GUI.
Mar 10 19:54:30 NOBLE-lnx bash[22]097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:54:30 NOBLE-lnx bash[22097]: Importing user_config.json...
Mar 10 19:54:30 NOBLE-lnx bash[22097]: Data from user_config.json imported successfully.
Mar 10 19:54:30 NOBLE-lnx bash[22097]: Running init command: gsettings set org.gnome.mutter overlay-key ''
Mar 10 19:54:30 NOBLE-lnx bash[22097]: Starting keyswap...
Mar 10 19:54:30 NOBLE-lnx bash[22097]: First window name: Gnome-terminal
Mar 10 19:54:30 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:54:33 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:54:33 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:54:33 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:54:34 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:54:34 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:54:35 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:54:35 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:54:37 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:54:43 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:54:43 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:54:43 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:55:03 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:03 NOBLE-lnx bash[22097]: gui: discord
Mar 10 19:55:06 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:07 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:55:07 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:08 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:55:13 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:13 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:55:13 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:55:45 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:45 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:55:47 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:55:47 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:47 NOBLE-lnx bash[22097]: gui: Code
Mar 10 19:55:49 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:49 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:55:50 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:50 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:56:17 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:17 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:56:19 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:19 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:56:19 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:56:20 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:20 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:56:23 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:23 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:56:23 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:56:30 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:30 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:56:31 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:31 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:56:31 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:56:41 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:41 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:56:44 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:44 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:56:44 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:56:52 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:52 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:57:12 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:57:12 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:57:12 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:57:12 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:57:16 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:57:16 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:57:22 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:57:22 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:57:22 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:58:49 NOBLE-lnx systemd[4802]: Stopping keyswap for Terminal and GUI...
Mar 10 19:58:49 NOBLE-lnx systemd[4802]: keyswap.service: Succeeded.
Mar 10 19:58:49 NOBLE-lnx systemd[4802]: Stopped keyswap for Terminal and GUI.
Mar 10 19:59:01 NOBLE-lnx systemd[4802]: Started keyswap for Terminal and GUI.
Mar 10 19:59:01 NOBLE-lnx bash[Mar 10 19:54:30 NOBLE-lnx systemd[4802]: Started keyswap for Terminal and GUI.
Mar 10 19:54:30 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:54:30 NOBLE-lnx bash[22097]: Importing user_config.json...
Mar 10 19:54:30 NOBLE-lnx bash[22097]: Data from user_config.json imported successfully.
Mar 10 19:54:30 NOBLE-lnx bash[22097]: Running init command: gsettings set org.gnome.mutter overlay-key ''
Mar 10 19:54:30 NOBLE-lnx bash[22097]: Starting keyswap...
Mar 10 19:54:30 NOBLE-lnx bash[22097]: First window name: Gnome-terminal
Mar 10 19:54:30 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:54:33 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:54:33 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:54:33 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:54:34 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:54:34 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:54:35 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:54:35 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:54:37 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:54:43 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:54:43 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:54:43 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:55:03 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:03 NOBLE-lnx bash[22097]: gui: discord
Mar 10 19:55:06 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:07 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:55:07 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:08 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:55:13 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:13 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:55:13 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:55:45 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:45 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:55:47 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:55:47 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:47 NOBLE-lnx bash[22097]: gui: Code
Mar 10 19:55:49 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:49 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:55:50 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:55:50 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:56:17 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:17 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:56:19 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:19 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:56:19 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:56:20 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:20 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:56:23 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:23 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:56:23 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:56:30 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:30 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:56:31 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:31 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:56:31 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:56:41 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:41 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:56:44 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:44 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:56:44 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:56:52 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:56:52 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:57:12 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:57:12 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:57:12 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:57:12 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:57:16 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:57:16 NOBLE-lnx bash[22097]: firefox: firefox
Mar 10 19:57:22 NOBLE-lnx bash[22097]: Internal error:   Could not resolve keysym XF86FullScreen
Mar 10 19:57:22 NOBLE-lnx bash[22097]: file /tmp/kinto/caret does not exist
Mar 10 19:57:22 NOBLE-lnx bash[22097]: term: Gnome-terminal
Mar 10 19:58:49 NOBLE-lnx systemd[4802]: Stopping keyswap for Terminal and GUI...
Mar 10 19:58:49 NOBLE-lnx systemd[4802]: keyswap.service: Succeeded.
Mar 10 19:58:49 NOBLE-lnx systemd[4802]: Stopped keyswap for Terminal and GUI.
Mar 10 19:59:01 NOBLE-lnx systemd[4802]: Started keyswap for Terminal and GUI.
Mar 10 19:59:01 NOBLE-lnx bash[23060]: Importing user_config.json...
Mar 10 19:59:01 NOBLE-lnx bash[23060]: Data from user_config.json imported successfully.
Mar 10 19:59:01 NOBLE-lnx bash[23060]: Running init command: gsettings set org.gnome.mutter overlay-key ''
Mar 10 19:59:01 NOBLE-lnx bash[23060]: Starting keyswap...
Mar 10 19:59:01 NOBLE-lnx bash[23060]: First window name: Gnome-terminal
Mar 10 19:59:01 NOBLE-lnx bash[23060]: term: Gnome-terminal
Mar 10 19:59:05 NOBLE-lnx bash[23060]: gui: discord
Mar 10 19:59:14 NOBLE-lnx bash[23060]: firefox: firefox
Mar 10 19:59:18 NOBLE-lnx bash[23060]: file /tmp/kinto/caret does not exist
Mar 10 19:59:18 NOBLE-lnx bash[23060]: gui: discord
Mar 10 19:59:19 NOBLE-lnx bash[23060]: firefox: firefox
Mar 10 19:59:19 NOBLE-lnx bash[23060]: term: Gnome-terminal
Mar 10 19:59:34 NOBLE-lnx bash[23060]: firefox: firefox
Mar 10 19:59:37 NOBLE-lnx bash[23060]: file /tmp/kinto/caret does not exist
Mar 10 19:59:38 NOBLE-lnx bash[23060]: file /tmp/kinto/caret does not exist
Mar 10 19:59:41 NOBLE-lnx bash[23060]: file /tmp/kinto/caret does not exist
Mar 10 19:59:41 NOBLE-lnx bash[23060]: term: Gnome-terminal
Mar 10 19:59:44 NOBLE-lnx bash[23060]: firefox: firefox
Mar 10 19:59:50 NOBLE-lnx bash[23060]: file /tmp/kinto/caret does not exist
Mar 10 19:59:50 NOBLE-lnx bash[23060]: term: Gnome-terminal
23060]: Importing user_config.json...
Mar 10 19:59:01 NOBLE-lnx bash[23060]: Data from user_config.json imported successfully.
Mar 10 19:59:01 NOBLE-lnx bash[23060]: Running init command: gsettings set org.gnome.mutter overlay-key ''
Mar 10 19:59:01 NOBLE-lnx bash[23060]: Starting keyswap...
Mar 10 19:59:01 NOBLE-lnx bash[23060]: First window name: Gnome-terminal
Mar 10 19:59:01 NOBLE-lnx bash[23060]: term: Gnome-terminal
Mar 10 19:59:05 NOBLE-lnx bash[23060]: gui: discord
Mar 10 19:59:14 NOBLE-lnx bash[23060]: firefox: firefox
Mar 10 19:59:18 NOBLE-lnx bash[23060]: file /tmp/kinto/caret does not exist
Mar 10 19:59:18 NOBLE-lnx bash[23060]: gui: discord
Mar 10 19:59:19 NOBLE-lnx bash[23060]: firefox: firefox
Mar 10 19:59:19 NOBLE-lnx bash[23060]: term: Gnome-terminal
Mar 10 19:59:34 NOBLE-lnx bash[23060]: firefox: firefox
Mar 10 19:59:37 NOBLE-lnx bash[23060]: file /tmp/kinto/caret does not exist
Mar 10 19:59:38 NOBLE-lnx bash[23060]: file /tmp/kinto/caret does not exist
Mar 10 19:59:41 NOBLE-lnx bash[23060]: file /tmp/kinto/caret does not exist
Mar 10 19:59:41 NOBLE-lnx bash[23060]: term: Gnome-terminal
Mar 10 19:59:44 NOBLE-lnx bash[23060]: firefox: firefox
Mar 10 19:59:50 NOBLE-lnx bash[23060]: file /tmp/kinto/caret does not exist
Mar 10 19:59:50 NOBLE-lnx bash[23060]: term: Gnome-terminal
```

And as you can see `/tmp/kinto/caret` does not exist...

**Comment by rbreaves** [comment]
@mlbaquerizo IBus appears to be surprisingly difficult to get fully configured on Manjaro Gnome. The main issue is that IBus not only needs to be installed and set as the default method, but the Panel extension needs to be there - but isn't and I have not been able to figure out what package or thing needs to exists or be set for the Panel to be there.

To set your IBus as the default method you can manually do this and logoff and back on. (I would have merged this as a fix already, but the panel being the other element prevents me from making any updates on this issue.)

```
IBus has been started! If you cannot use IBus, please add below lines in ~/.bashrc, and relogin your desktop.
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
```

You can do your own testing, if you want, by running these two commands out of the caret_status.sh file.

```
# org.freedesktop.ibus.panel

IBUSADD=$(cat ~/.config/ibus/bus/`ls ~/.config/ibus/bus -1rt | tail -n1` | awk -F'IBUS_ADDRESS=' '{print $2}' | xargs)

dbus-monitor --address $IBUSADD "path='/org/freedesktop/IBus/Panel',interface='org.freedesktop.IBus.Panel',member='FocusOut'" 2> /dev/null | grep --line-buffered -o -P '(?<=object path \"/org/freedesktop/IBus/InputContext_).*(?=[\"])'
```

org.freedesktop.IBus can be inspected using d-feet, but that hasn't told me much. If anyone has any ideas it would be appreciated and I'll merge the fix in.

https://wiki.archlinux.org/index.php/IBus

**Comment by rbreaves** [comment]
@mlbaquerizo It looks like the ~/.bashrc file should be using xim, that lines up with PopOS and probably others when they are configured to use IBus. It seems Firefox is jailed in a way that only allows for xim to work with it. This still doesn't resolve the actual problem though, at least not for me - the input caret is still not being detected, I suspect the Panel is still missing.

I am not sure why it looks like Pop_OS has the IBus service running twice, but it does work fine in Pop_OS.

```
IBus has been started! If you cannot use IBus, please add below lines in ~/.bashrc, and relogin your desktop.
export GTK_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=xim
```
Pop_OS 19.10
<img width="1129" alt="Screen Shot 2020-03-11 at 5 14 38 PM" src="https://user-images.githubusercontent.com/10969616/76469246-e463c780-63bb-11ea-8783-7f8acd61d5f7.png">

Manjaro Gnome 19.10
<img width="956" alt="Screen Shot 2020-03-11 at 5 15 04 PM" src="https://user-images.githubusercontent.com/10969616/76469279-f5acd400-63bb-11ea-8396-24e6eadc6795.png">

**Comment by rbreaves** [comment]
Switching windows within a particular window group on XFCE and DE's that do not support it directly. Map Ctrl+` or Ctrl+Shift+` to it.

https://bbs.archlinux.org/viewtopic.php?id=181646
